### ISSUE TITLE
如何将引用的数字式上标改为author-year式

### ISSUE THREAD

**Issue by nirvanaxiao6** [thomas10011/WHU-Beamer#2]
我在整个文档中没有找到有关参考文献格式的.bst文件，请问在哪里可以更改参考文献生成的格式呢？

**Comment by hrtan99** [comment]
项目中使用了biblatex包自动生成参考文献及其引用，上标的代码位于样式文件中，

```latex
% 重写上标引用命令。请勿随意改动括号缩进。
\DeclareCiteCommand{\supercite}[\mkbibsuperscript]
  {\bibopenbracket
    \usebibmacro{cite:init}%
    \let\multicitedelim=\supercitedelim
    \iffieldundef{prenote}{}
      {\BibliographyWarning{Ignoring prenote argument}}%
    \iffieldundef{postnote}{}
      {\BibliographyWarning{Ignoring postnote argument}}}
  {\usebibmacro{citeindex}\usebibmacro{cite:comp}}
  {}
  {\usebibmacro{cite:dump}\bibclosebracket}
```

而根据stackexchange上的[相关讨论](https://tex.stackexchange.com/questions/585635/beamer-biblatex-authoryear-causes-problem-with-insertbiblabel)，目前在beamer文档中使用biblatex可能无法像article文档那样兼容上标author-year形式的引用格式。所以很抱歉，目前无法提供上标author-year形式的引用支持。如果你找到了解决方法，欢迎提交PR👏🏻
