### ISSUE TITLE
请教封面出处

### ISSUE THREAD

**Issue by lemyx** [thomas10011/WHU-Beamer#3]
作者您好，

感谢这个开源repo，非常美观！

我不是武汉大学的学生，因此想对封面进行修改。
可以请问封面的出处吗？ (即带有校训的浅灰色4K图片)

谢谢！

**Comment by hrtan99** [comment]
你好，封面是我用Photoshop自己P的，具体的方法你可以查一下「图片转线稿」

**Comment by thomas10011** [comment]
Problem Solved.
